name: Generate Investment Report

on:
  schedule:
    - cron: '0 17 * * *'  # 台灣時間凌晨1點（UTC+8）
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script to generate report
      run: python analyze_stock.py

    - name: Commit and Push report
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/投資損益分析報告.html
        git commit -m "Auto-update report $(date '+%Y-%m-%d %H:%M:%S')"
        git push
      continue-on-error: true
