name: Generate Investment Report

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 16 * * *'  # 每天台灣 09:01 自動執行
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Noto Sans CJK TC font
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script to generate report
      run: python analyze_stock.py

    - name: Commit and Push report
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/
        git commit -m "Auto-update report $(date '+%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
        git push
      continue-on-error: true
