name: Generate Investment Report

on:
  schedule:
    # 每天凌晨1點跑（UTC時間），可自行調整
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run analyze_stock.py to generate report
      run: python analyze_stock.py

    - name: Commit and push report
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add 投資損益分析報告.html
        git commit -m "自動更新投資損益分析報告 $(date)"
        git push
      continue-on-error: true
